development: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  host: localhost

  username: crea_user
  password: creapass

  database: crea

test:
  <<: *default

production:
  <<: *default
